USE [master]
GO

/****** Object:  Database [CarRental]    Script Date: 09.03.2019 11:27:13 ******/
CREATE DATABASE [CarRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRental', FILENAME = N'D:\work\CarRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarRental_log', FILENAME = N'D:\work\CarRental_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CarRental] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRental] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRental] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarRental] SET  MULTI_USER 
GO

ALTER DATABASE [CarRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRental] SET QUERY_STORE = OFF
GO

USE [CarRental]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CarRental] SET  READ_WRITE 
GO

USE [CarRental]
GO

/****** Object:  Table [dbo].[Cars]    Script Date: 09.03.2019 11:27:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cars](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Brand] [nvarchar](250) NOT NULL,
	[Model] [nvarchar](250) NOT NULL,
	[Сlass] [nvarchar](100) NOT NULL,
	[Year] [int] NOT NULL,
	[RegistrationNumber] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



/****** Object:  Table [dbo].[Users]    Script Date: 09.03.2019 11:28:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Surname] [nvarchar](200) NOT NULL,
	[Birth] [date] NOT NULL,
	[LicenseNumber] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[Orders]    Script Date: 09.03.2019 11:28:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CarId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[BeginDate] [date] NOT NULL,
	[EndDate] [date] NULL,
	[Comment] [nvarchar](max) NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Cars] FOREIGN KEY([CarId])
REFERENCES [dbo].[Cars] ([Id])
GO

ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Cars]
GO

ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Users]
GO


